@startuml

start

: Include Ultrasonic Sensor HCSR04 library in Arduino IDE;
: Set the trigger pin and the echo pin of HCSR04 sensor;
: Set the builtin LED of Arduino board as output;

repeat
: Call the distance function from HCSR04 library and Store the value of distance in a variable;
: Now display the value of distance variable;

if (is distance less than 10) then (yes)
    while(is count less than or equal to 9) is (yes)
        : Set the LED on HIGH for few microseconds;
        : Then set the LED on LOW for few microseconds;
    end while

elseif (is distance greater than 10 and is distance less than 30) then (yes)
    while(is count less than or equal to 5) is (yes)
        : Set the LED on HIGH for few microseconds;
        : Then set the LED on LOW for few microseconds;
    end while

else (No)
    while (is count less than or equal to 2) is (yes)
        :Set the LED on HIGH for few microseconds;
        :Then set the LED on LOW for few microseconds;
    end while
endif

repeat while

@enduml